on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        uses: py-actions/py-dependency-install@v3
        with:
            path: "requirements.txt"
      - name: Test with pytest
        run: |
          pip install pytest 
          pytest
